version: '3'

services:
  scroll-syncer:
    build:
      context: .
      dockerfile: synchronizer/Dockerfile
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
